-
  name: Deploy a mysql DB
  hosts: db_server
  roles:
    - python
    - mysql_db

-
  name: Deploy a Web Server
  hosts: web_server
  roles:
    - python
    - flask_web

-
  name: Monitor Web Application for 6 Minutes
  hosts: web_server
#   command: /opt/monitor_webapp.py
#   async: 360  # To make async connections to the Servers, so that the SSH is not open.
#   poll: 0 # start the task and move to text , if we dont have dependency
#   register: webapp_result # register the results , so that can be verfied later with jid = {{web_result.ansible_job_id}}
-
  name: Monitor Database for 6 Minutes
  hosts: db_server
#   command: /opt/monitor_database.py
#   async: 360
#   poll: 0
#   register: database_result